### ISSUE TITLE
 Error: Driver 'bcm63xx-spi' is already registered, aborting...

### ISSUE THREAD

**Issue by witoldo7** [pgid69/bcm63xx-phone#1]
image by
http://downloads.openwrt.org/snapshots/trunk/brcm63xx/smp/OpenWrt-ImageBuilder-brcm63xx-smp.Linux-x86_64.tar.bz2
package by
http://downloads.openwrt.org/snapshots/trunk/brcm63xx/smp/OpenWrt-SDK-brcm63xx-smp_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2

http://pastebin.com/TBgLN4Xw

**Comment by pgid69** [comment]
The driver implements manages SPI bus its own way (more efficient than bcm63xx-spi driver), so it conflicts with driver bcm63xx-spi
You must rmmod bcm63xx-spi if you want to insmod bcm63xx-phone
