### ISSUE TITLE
can compile with sip stack and then register to sip servers for voip?

### ISSUE THREAD

**Issue by cubieb** [pgid69/bcm63xx-phone#11]
Thanks for your opensource project, that is really a good job. 
the hg556a origin firmware support a sip client then we can register to sip server on the internet

can we port some sip stack to impliment that functions?

thanks,
bob

**Comment by pgid69** [comment]
bcm63xx-phone is a kernel module that is intended to be used with the Asterisk channel i developped. The SIP stack is in Asterisk. It's Asterisk that register to a SIP server.
I don't understand what you mean by "can we port some sip stack" ? What do you want to do ?

**Comment by cubieb** [comment]
I know， Asterisk at here is just like a sip proxy， if i do not install asterisk， can we setup the sip call   success？

**Comment by pgid69** [comment]
No without Asterisk, no SIP stack, so no SIP call.
