### ISSUE TITLE
Huawei HG556A works fine

### ISSUE THREAD

**Issue by YPKEH** [pgid69/bcm63xx-phone#15]
OpenWRT Barrier Breaker 14.07
HG55VDFA VER.C Router version B (see https://wiki.openwrt.org/toh/huawei/hg556a)

Patched for disable SPI - **its very important**.:
-CONFIG_SPI_BCM63XX=y
+CONFIG_SPI_BCM63XX=n

You have to load bcm63xx-phone.ko **before start** asterisk:
my rc.local starting script:

insmod bcm63xx-phone.ko
sleep 10
/etc/init.d/asterisk start
exit 0

Asterisk 11, excelent voice quality.

**Thanks for pgid69**

**Comment by pgid69** [comment]
Thank you very much for your feedback.

**Comment by talnacialex** [comment]
I have to say that it also works on my router. I finally managed to compile it. Works very good.

**Comment by crdlight** [comment]
I have a Huawei HG556A can anyone share the config files to enable fxs on it.
thank you
