### ISSUE TITLE
Cannot compile on LEDE latest version

### ISSUE THREAD

**Issue by talnacialex** [pgid69/bcm63xx-phone#28]
Hi there. I am updating my LEDE firmware of the VoIP box(of course, it runs bcm63xx-phone), and it seems that the patch files aren't working anymore and also, it stopped compiling properly. It mentioned something about struct condition done in the mpi file.

How we can fix this?
BR,
Talnaci Alexandru

**Comment by talnacialex** [comment]
Forgot to mention the OS I am using to compile on:

Linux Mint 19 Tara - it's Ubuntu-based OS, Ubuntu 18.04

**Comment by talnacialex** [comment]
the VoIP box is HW556 ver C

**Comment by pgid69** [comment]
Hello

I will put patches for 18.06 branch of OpenWrt as soon as possible.
But if you want to compile the firmware without the patch you just have to launch 
make kernel_menuconfig
and change state of "Device drivers/SPI Support/Broadcom 63xx SPI Controller" : new state should be M for module or N if you don't need the module

BR

**Comment by pgid69** [comment]
Hello

I've just added the patches for 18.06 branch of OpenWrt.
Tell me if it's ok or not.

Thank you

BR

**Comment by talnacialex** [comment]
I will compile right now and see if the problem persists.

Thank you!
Best Regards,

Talnaci Alexandru

**Comment by talnacialex** [comment]
Ok, so the patches work, but now it remains that error I talked about earlier. struct completion done;

Log: https://pastebin.com/cEceyLk0

**Comment by pgid69** [comment]
With the log it's easier to understand and fix your problem !

From the log i can see that you are compiling for Linux 4.14.
I made my tests with Linux 4.9 (the kernel used with platform brcm63xx in the 18.06 branch of OpenWrt) and that's why i didn't encounter your problem.
Whatsoever, i've just pushed a new commit that should fix the error you have.
The compilation is still ok for Linux 4.9

BR

**Comment by r0neko** [comment]
Ok! I will try to compile the new version and tell you if it succeded or not.

BR.

**Comment by r0neko** [comment]
Yes, it compiled successfully now. Thank you for making this amaizing driver. I don't know why LEDE/OpenWRT team did not add support for this driver. 

BR, 
Talnaci Alexandru

**Comment by pgid69** [comment]
Hello

Just a small question related to issue #26 submitted by user @lulol : does both FXS ports work or just only one ?

Thanks

Gilles
