### ISSUE TITLE
How to dial to  FXS lines

### ISSUE THREAD

**Issue by dotmark** [pgid69/bcm63xx-phone#3]
When i dial "100" from a SIP phone,  i want FXS line1 ring.
How to config extensions.conf ?

[bcmph-line-1] 
exten => 100,1,Dial(?[to FXS line1])
exten => 200,1,Dial(SIP/Mytest)

I`m not familiar with the asterisk. Thank you.

**Comment by pgid69** [comment]
I'm not familiar with Asterisk either.
But for your problem, section [bcmph-line-1] is for handling calls initiated from the FXS line.
In your case you should have a section dedicated to your SIP phone with the following line
exten => 100,1,Dial(Bcm63xxPhone/1)

**Comment by pgid69** [comment]
One remarks : you can launch the asterisk console to watch what's happen when you dial 100 from your SIP phone : asterisk -rvvvvvv

**Comment by dotmark** [comment]
Succeed！

**Comment by pgid69** [comment]
I will investigate the problem of phone 1 that can't be enabled

**Comment by pgid69** [comment]
On the HW553, FXS port "Phone 1" is line 2 and "Phone 2" is line 1. So i change file board.c to swap id of lines of HW553.
Else i can enable the two lines in Asterisk.
