### ISSUE TITLE
problem dahdi in router hg556 Failed probing type for channel 1 at perl_modules/Dahdi/Config/Gen/System.pm line 238

### ISSUE THREAD

**Issue by elen100** [pgid69/bcm63xx-phone#37]
i am Successfully  install driver dahdi in router hg556

logread
------------------------------------------------------------------------------------------------------------------------------------------------
bcm63xx_phone_dahdi zarlink_wait_for_event() 340: Received VP_EVID_CAL_CMP event (i = 1180)
[   37.750030] bcm63xx_phone_dahdi zarlink_wait_for_event() 354: Found event: pEvent.eventCategory = 2 pEvent.eventId = 64 
[   37.761351] bcm63xx_phone_dahdi zarlink_set_timeslot_and_codec() 272: zarlink_set_timeslot_and_codec(codec_type=0, ts=0)
[   37.772829] bcm63xx_phone_dahdi zarlink_slic_line_init() 658: FXS line initialized OK
[   37.780983] bcm63xx_phone_dahdi zarlink_slic_line_init() 586: zarlink_slic_line_init(country=0, codec=1, timeslot=2)
[   37.794727] bcm63xx_phone_dahdi zarlink_wait_for_event() 316: zarlink_wait_for_event(evt_category=2, evt_id=2048)
[   37.805535] bcm63xx_phone_dahdi zarlink_wait_for_event() 337: Received VP_LINE_EVID_LINE_INIT_CMP event (i = 0)
[   37.816033] bcm63xx_phone_dahdi zarlink_wait_for_event() 354: Found event: pEvent.eventCategory = 2 pEvent.eventId = 2048 
[   37.828159] bcm63xx_phone_dahdi zarlink_wait_for_event() 316: zarlink_wait_for_event(evt_category=2, evt_id=64)
[   39.888335] bcm63xx_phone_dahdi zarlink_wait_for_event() 340: Received VP_EVID_CAL_CMP event (i = 1180)
[   39.898111] bcm63xx_phone_dahdi zarlink_wait_for_event() 354: Found event: pEvent.eventCategory = 2 pEvent.eventId = 64 
[   39.909414] bcm63xx_phone_dahdi zarlink_set_timeslot_and_codec() 272: zarlink_set_timeslot_and_codec(codec_type=0, ts=2)
[   39.920887] bcm63xx_phone_dahdi zarlink_slic_line_init() 658: FXS line initialized OK
[   39.929170] bcm63xx_phone_dahdi phone_dev_zarlink_get_hook_status() 1877: Line 0 is on hook
[   39.938140] bcm63xx_phone_dahdi phone_dev_zarlink_get_hook_status() 1877: Line 1 is on hook
[   39.947027] bcm63xx_phone_dahdi bcm_periodic_timer_add_work() 181: bcm_periodic_timer_add_work(period_in_us=10000)
[   39.957777] bcm63xx_phone_dahdi bcm_period_set_period() 42: bcm_period_set_period(period_in_usecs=10000)
[   39.967520] bcm63xx_phone_dahdi bcm_period_set_period() 61: one_jiffy_to_usecs=4000, period_in_jiffies=3, real_period=12000, drift_increment=2000
[   39.981182] bcm63xx_phone_dahdi bcm_dahdi_startup() 914: bcm_dahdi_startup()
[   39.988503] bcm63xx_phone_dahdi bcm_periodic_timer_add_work() 181: bcm_periodic_timer_add_work(period_in_us=1000)
[   39.999127] bcm63xx_phone_dahdi bcm_period_set_period() 42: bcm_period_set_period(period_in_usecs=1000)
[   40.008780] bcm63xx_phone_dahdi bcm_period_set_period() 61: one_jiffy_to_usecs=4000, period_in_jiffies=1, real_period=4000, drift_increment=3000
[   40.022205] bcm63xx_phone_dahdi bcm63xx_phone_dahdi_init() 1188: bcm63xx_phone_dahdi successfully initialized
[   40.047871] bcm63xx_phone_dahdi bcm_dahdi_set_line_mode() 481: bcm_dahdi_set_line_mode(line=0, mode=2, reverse_polarity=0)
[   40.059425] bcm63xx_phone_dahdi bcm_dahdi_set_line_mode() 481: bcm_dahdi_set_line_mode(line=1, mode=2, reverse_polarity=0) 

---------------------------------------------------------------------------------------------------------------------------------------------------------

root@LEDE:/tmp/dahdi-tools-2.11.1/xpp# ./lsdahdi
### Span  1: bcm63xx_phone_dahdi/1 "FXS driver for brcm63xx" (MASTER) 
  1 unknown                 
  2 unknown  

root@LEDE:/tmp/dahdi-tools-2.11.1# ./dahdi_scan
[1]
active=yes
alarms=UNCONFIGURED
description=FXS driver for brcm63xx
name=bcm63xx_phone_dahdi
manufacturer=ACME
devicetype=bcm63xx_phone_dahdi
location=
basechan=1
totchans=2
irq=0
type=analog
port=1,FXS
port=2,FXS

root@LEDE:/tmp/dahdi-tools-2.11.1/xpp# ./dahdi_genconf
Failed probing type for channel 1 at perl_modules/Dahdi/Config/Gen/System.pm line 238

**Comment by pgid69** [comment]
I can't help you with error you get with System.pm.
However the log shows driver loads successfully, and dahdi_scan detects the two channels provided by bcm63xx_phone_dahdi

For my tests, my conf was :
- in /etc/asterisk/chan_dahdi.conf i just added at the end of the file the line
`#include /etc/asterisk/dahdi-channels.conf`
- and the content of the file /etc/asterisk/dahdi-channels.conf is
```
; Dahdi Channels Configurations (chan_dahdi.conf)
;
; This is not intended to be a complete chan_dahdi.conf. Rather, it is intended
; to be #include-d by /etc/chan_dahdi.conf that will include the global settings
;

; Span 1: bcm63xx_phone_dahdi/1 "FXS driver for brcm63xx" (MASTER)
;;; line="1 bcm63xx_phone_dahdi/1/0 FXOLS"
signalling=fxo_ks
callerid="Channel 1" <4001>
mailbox=4001
group=5
context=from-internal
channel => 1
callerid=
mailbox=
group=
context=default

;;; line="2 bcm63xx_phone_dahdi/1/1 FXOLS"
signalling=fxo_ks
callerid="Channel 2" <4002>
mailbox=4002
group=5
context=from-internal
channel => 2
callerid=
mailbox=
group=
context=default
```
It defines 2 DAHDI channels. The lines
```
callerid=
mailbox=
group=
context=default
```
are just intended to reset the config

The rest is just Asterisk configuration. 
Good luck.
