### ISSUE TITLE
Regional tones

### ISSUE THREAD

**Issue by Leoz83** [pgid69/bcm63xx-phone#7]
Hi, i've try to set
`country = italy`
on bcm63xx_phone.conf

I've already set
`country=it`
on indications.conf, but when i pick up the phone  the configuration not work.
HW553 - asterisk11

Suggestions?
Thanks for all your work!

**Comment by pgid69** [comment]
Hi,
The parameter country has no effect on dial tones.
It only has effects on voltages... It's used by the Voice Path API Lite SDK to select AC, DC profiles.
The dial tones are hard coded and do not depend upon the parameter country.
Is it really important ?

BR

**Comment by Leoz83** [comment]
Nothing of important, just for habit

**Comment by pgid69** [comment]
Hello

I finally add an option in bcm63xx-phone.conf to choose the zone, allowing to have tone and ring cadence specific to your country as defined in file indications.conf.
If option zone is not set it is derived from option country if possible.

BR
